version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8085:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
